package ru.spb.iac.ldapname;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T17:05:27.474+04:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "NewLdapService", 
                  wsdlLocation = "file:/home/normal/IdeaProjects/LdapServiceGit/GeneratedClasses/xml/LDAPws.wsdl",
                  targetNamespace = "http://iac.spb.ru/LDAPname") 
public class NewLdapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://iac.spb.ru/LDAPname", "NewLdapService");
    public final static QName NewLdapPort = new QName("http://iac.spb.ru/LDAPname", "NewLdapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/normal/IdeaProjects/LdapServiceGit/GeneratedClasses/xml/LDAPws.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NewLdapService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/normal/IdeaProjects/LdapServiceGit/GeneratedClasses/xml/LDAPws.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NewLdapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NewLdapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewLdapService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NewLdapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NewLdapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NewLdapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NewLdapPort
     */
    @WebEndpoint(name = "NewLdapPort")
    public NewLdapPort getNewLdapPort() {
        return super.getPort(NewLdapPort, NewLdapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewLdapPort
     */
    @WebEndpoint(name = "NewLdapPort")
    public NewLdapPort getNewLdapPort(WebServiceFeature... features) {
        return super.getPort(NewLdapPort, NewLdapPort.class, features);
    }

}
